example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name="show_json"),
    path('xml/<int:id>', show_xml_id, name='show_xml_id'),
    path('json/<int:id>', show_json_id, name="show_json_id"),
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('login/', login_user, name='login'),
    path('ajax/submit/', create, name='tbl-form'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
# Create your models here.
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http.response import JsonResponse
# Create your views here.

data_barang_wishlist = BarangWishlist.objects.all()

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Yudi :D',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Yudi :D',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/wishlist/login/')
def create(request):
    if request.method == 'POST':
        nama_barang = request.POST.get('nama_barang')
        harga_barang = request.POST.get('harga_barang')
        deskripsi = request.POST.get('deskripsi')
        item = BarangWishlist(nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi)
        item.save()
        return JsonResponse({"instance": "Proyek Dibuat"}, status=200)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg bg-warning">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">{{nama}}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>

        </div>
    </nav>
    <div class="d-flex justify-content-center">
    <h5>Nama:  {{nama}} </h5>
    </div>

    <table class="table-striped-columns table-bordered d-flex justify-content-center ">
        <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
        {% endfor %}
    </table>
    <h5 class="d-flex justify-content-center">Sesi terakhir login: {{ last_login }}</h5>
  </body>
</html>
    

wishlist/templates/wishlist_ajax.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg bg-warning">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">{{nama}}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>
        </div>
    </nav>
    <div class="d-flex justify-content-center">
    <h5>Nama:  {{nama}} </h5>
    </div>

    <table class="table-striped-columns table-bordered d-flex justify-content-center" id="tbl">
    </table>
    <h5 class="d-flex justify-content-center">Sesi terakhir login: {{ last_login }}</h5>

    <div>
      <form method="POST" action="" id="formtable" class="d-flex justify-content-center p-2  ">
        <div class="bg-danger d-flex justify-content-center p-2 rounded-2 p-3">
          {% csrf_token %}
          <table>
            <tr>
                <td>Nama Barang: </td>
                <td><input type="text" name="items" placeholder="Nama Barang" class="form-control" id="items_name"></td>
            </tr>
            <tr>
                <td>Harga Barang: </td>
                <td><input type="text" name="items_price" placeholder="Harga Barang" class="form-control" id="items_pr"></td>
            </tr>
            <tr>
                <td>Deskripsi: </td>
                <td><input type="text" name="items_desc" placeholder="Deskripsi" class="form-control" id="items_descrip"></td>
            </tr>
            
            
            </table>
            <button onclick="clickCounter()" type="submit" id="masuk" class="btn border rounded bg-info mx-2">Tambah</button>
        </div>
      
        
      </form>
     </div> 
  </body>
</html>
    
<script>

let tab;
  function loadData() {
    $.get("{% url 'wishlist:show_json' %}", function (data) {
      tab = `<tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
          </tr>`;

      for (let item of data) {
        tab += `<tr> 
        <td>${item.fields.nama_barang} </td>
        <td>${item.fields.harga_barang}</td>
        <td>${item.fields.deskripsi}</td> 
        </tr>`;}

    document.getElementById("tbl").innerHTML = tab;
    });
  }

  $(document).ready(function () {
    loadData();
  });

  $(document).on("submit", "#formtable", function (e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: "{% url 'wishlist:tbl-form' %}",
      data: {
        nama_barang: $("#items_name").val(),
        harga_barang: $("#items_pr").val(),
        deskripsi: $("#items_descrip").val(),
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      dataType: "json",
      success: function () {
        loadData();
      },
    });
  });

  function clickCounter() {
    if (localStorage.clickcount) {
        localStorage.clickcount = Number(localStorage.clickcount)+1;
    } else {
        localStorage.clickcount = 1;
    }
}
</script>